bind-key -n '$' switch-client -T ctrl
bind-key -T ctrl a send-key C-a
bind-key -T ctrl b send-key C-b
bind-key -T ctrl c send-key C-c
bind-key -T ctrl d send-key C-d
bind-key -T ctrl e send-key C-e
bind-key -T ctrl f send-key C-f
bind-key -T ctrl g send-key C-g
bind-key -T ctrl h send-key C-h
bind-key -T ctrl i send-key C-i
bind-key -T ctrl j send-key C-j
bind-key -T ctrl k send-key C-k
bind-key -T ctrl l send-key C-l
bind-key -T ctrl m send-key C-m
bind-key -T ctrl n send-key C-n
bind-key -T ctrl o send-key C-o
bind-key -T ctrl p send-key C-p
bind-key -T ctrl q send-key C-q
bind-key -T ctrl r send-key C-r
bind-key -T ctrl s send-key C-s
bind-key -T ctrl t send-key C-t
bind-key -T ctrl u send-key C-u
bind-key -T ctrl v send-key C-v
bind-key -T ctrl w send-key C-w
bind-key -T ctrl x send-key C-x
bind-key -T ctrl y send-key C-y
bind-key -T ctrl z send-key C-z
bind-key -T ctrl Space send-key C-Space
bind-key -T ctrl Space send-key C-Space

bind-key -T ctrl '$' send-key '$'
